### ISSUE TITLE
TypeError: Cannot read property 'matchesNode' of null

### ISSUE THREAD

**Issue by wolfplus** [sibiraj-s/ngx-tiptap#25] opened 2022-03-23 10:26 UTC
Hello, i found that this error is trigerrd when you destroy then you create the editor. It seems to have been solved in other farmework like react etc, but i guess in angular is not fixed yet

**Comment by sibiraj-s** [comment] 2022-03-31 13:00
Could you provide a reproducible code for this? may be a stackblitz?

**Comment by sibiraj-s** [comment] 2022-05-07 13:03
This issue is because the component itself destroys the editor on unmount. Fix would be a breaking change.

**Comment by sibiraj-s** [comment] 2022-05-07 15:34
Should be fixed in v5. 

Note: Editor must be manually destroyed.

**Closed by sibiraj-s** 2022-05-07 15:34 UTC
