### ISSUE TITLE
Cannot reconcile build once Tiptap extensions are added

### ISSUE THREAD

**Issue by Routhinator** [sibiraj-s/ngx-tiptap#42] opened 2023-07-17 14:56 UTC
Hey there, looking for some guidance on getting extensions into ngx-tiptap without tripping on myself here. I know the docs say "read the tiptap docs" - but doing that has led me to this and I cannot seem to resolve it.

```
Error: node_modules/@tiptap/pm/node_modules/prosemirror-view/dist/index.d.ts:215:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'pmViewDesc' must be of type 'ViewDesc', but here has type 'ViewDesc'.

215         pmViewDesc?: ViewDesc;
            ~~~~~~~~~~

  node_modules/prosemirror-view/dist/index.d.ts:215:9
    215         pmViewDesc?: ViewDesc;
                ~~~~~~~~~~
    'pmViewDesc' was also declared here.
```

I've gone through the package.json for `ngx-tiptap@9.0.1` and aligned my versions so that they are all at `2.0.4` and I have this:

```
    "@tiptap/extension-document": "2.0.4",
    "@tiptap/extension-heading": "2.0.4",
    "@tiptap/extension-paragraph": "2.0.4",
    "@tiptap/extension-placeholder": "2.0.4",
    "@tiptap/extension-text": "2.0.4",
    "ngx-tiptap": "9.0.1",
```

Yet it looks like somehow I have at least 6 versions of `prosemirror-view` being referenced in my resulting package.lock and that leads me to wonder if I've missed something in the directions because with that much variance in dependencies from packages that are all pinned to the same version series, it seems off...

![image](https://github.com/sibiraj-s/ngx-tiptap/assets/727535/2f35a4c8-e47a-4836-a92f-cfa2ce42d476)

**Comment by sibiraj-s** [comment] 2023-07-18 05:01
Glad you fixed it. Some of this issue happens while updating the packages either angular or tiptap. Leaving some takeaways from my earlier encounter with similar issue. The following helped solve the issue, the issue is not with the editor

Some ways to fix this.
- delete lock file and node_modules and do npm install again, this way npm does a clean install removing duplicate entries
- verify your typescript version. make sure it is same as the one angular recommends for its version. You refer this repo for the version.
- check your typescript config, refer this repository's tsconfig.json for sample config

if you'd like to use prosemirror packages consider using [@tiptap/pm](https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/ngx-tiptap/package.json#L25) package instead so you don't get duplicate packages or need to keep up with prosemirror and tiptap updates. Its just a re-export of prosemirror-* packages

Closing this issue as this is not an issue with the package. Feel free to continue the conversation if required. Thank you.

**Closed** 2023-07-18 05:01 UTC
