### ISSUE TITLE
ngModelChange gets emitted initially, without actual value change

### ISSUE THREAD

**Issue by Maximaximum** [sibiraj-s/ngx-tiptap#24] opened 2022-02-11 09:39 UTC
Hi! Thanks a lot for the awesome lib!

I've found something that looks like a bug.

Please see the demo here: https://stackblitz.com/edit/ngx-tiptap-ngmodelchange-initial?file=README.md

The tiptap-editor behavior is different from standard Angular behavior with regards to the `ngModelChange` event. The `ngModelChange` event gets emitted once from a `ngx-tiptap` editor instance on initial component load, even though the component has not been touched by the user and there have been no changes to the initial value yet.

It would be great if this could be fixed so that the `ngModelChange` only gets emitted on actual value changes. Otherwise this breaks the validation and many other scenarios.

Thanks!

**Comment by sibiraj-s** [comment] 2022-02-11 10:06
Hi,

Yeah. This is a bug in angular I guess. During initial render, when ngModel, is used [writeValue accessor](https://angular.io/api/forms/ControlValueAccessor#writeValue) is called with an arbitrary `null` value.

I could ignore if the value is `null` and don't emit the change, but the reactive forms use the same value `null` when `form.reset()`. Couldn't differentiate the both, hence this issue exists. This doesn't happen with reactive forms though.

**Comment by Maximaximum** [comment] 2022-02-11 10:11
Hm, do you have an idea how this is handled within the stanard Angular controls like `<input>` or `<textarea>`?

**Comment by Maximaximum** [comment] 2022-02-15 12:50
Hi @sibiraj-s!

Just wondering if you would have some time to look into this issue soon?

I'm considering replacing the quilljs library in my project with something else, and it looks like I'll have to choose whether to use `tiptap` and `ngx-tiptap` depending on whether this issue can be resolved.

Is there anything I can help you with?

**Comment by sibiraj-s** [comment] 2022-02-15 13:24
HI, @Maximaximum Sorry I didn't get back on this. I missed the notification on your reply. My Mac is under service. It would take a week to get it back.

I would appreciate any kind of help.

https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/ngx-tiptap/src/lib/editor.directive.ts#L26. This is the function that angular invokes whenever a value changes, You can start here. I am also open to workarounds if that fixes the issues cleanly.

> Hm, do you have an idea how this is handled within the stanard Angular controls like <input> or <textarea>?

I didn't go through it yet. Its a pretty big codebase to look around and I couldn't find enough time to poke around.

> it looks like I'll have to choose whether to use tiptap and ngx-tiptap depending on whether this issue can be resolved.

How disruptive is this issue? I have been using reactive forms myself. which doesn't have this issue. Is that an option for you (atleast temporarily)?

**Comment by Destreyf** [comment] 2022-03-10 20:41
Just to follow up, I ran into this issue as well.  I am only using ngModel for very simple pages/controls and I can confirm that using a Reactive FormGroup works as expected.  

It appears this may be the culprit: https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/ngx-tiptap/src/lib/editor.directive.ts#L71-L83

It looks like "setContent" is being called on the value of the inner HTML, so if there's not a value it never appears to actually get a value.

**Comment by sibiraj-s** [comment] 2022-12-22 16:12
Fixed in v7.0.0

**Closed by sibiraj-s** 2022-12-22 16:12 UTC
