### ISSUE TITLE
Components not rendering inside the editor

### ISSUE THREAD

**Issue by CondensedMilk7** [sibiraj-s/ngx-tiptap#39] opened 2023-07-06 17:45 UTC
Here's a minimal reproduction link:
https://stackblitz.com/edit/stackblitz-starters-ssgbis?file=src%2Fmain.ts

The only difference here is that standalone components are used but module-based components had similar issues. The component is simply not rendered in the template.

It is also interesting why the component to be displayed in the editor doesn't have a template in the documentation.

I might be missing something here, or this is possibly a bug.

**Comment by sibiraj-s** [comment] 2023-07-07 06:12
Make sure to add group to the extension.

See example here https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/demo/src/app/nodeview-renderer/extensions.ts#L11

It tested in your stackblitz and it works, so closing it as this is not a bug.

**Closed by sibiraj-s** 2023-07-07 06:12 UTC

**Comment by CondensedMilk7** [comment] 2023-07-07 08:46
> Make sure to add group to the extension.
> 
> See example here https://github.com/sibiraj-s/ngx-tiptap/blob/master/projects/demo/src/app/nodeview-renderer/extensions.ts#L11
> 
> It tested in your stackblitz and it works, so closing it as this is not a bug.

Thanks! I think this example should be moved to `README.md`. As is, it implicitly relies on the user knowing node views of tiptap to begin with, so with a quick and ignorant setup people like me shoot themselves in the foot.

**Comment by sibiraj-s** [comment] 2023-07-07 10:23
Sure. But its recommended to refer tiptap dics for creating extensions and for everything, its not possible to document everything here, its just a wrapper for the other tool.  

May be I can make a note of it somewhere, but its really not possible to provide examples on all cases.

**Comment by sibiraj-s** [comment] 2023-07-07 11:43
I've updated the README code with a comment https://github.com/sibiraj-s/ngx-tiptap#create-a-node-extension to avoid confusions and also provided a link on how to create custom extensions.

Thanks for the suggestion.
